name: Main Workflow
on: [push]
jobs:
  build:
    name: Run NosyMouse tests
    runs-on: ubuntu-latest
    steps:
      - name: Install NosyMouse CLI
        run: |
          curl https://github.com/myllil/NOSYMOUSE-CLI/blob/3adc73766b6a2f8ff370fa02c25416075075b666/nosymouse-linux-x64.zip -L | unzip -q nosymouse-linux-x64.zip
      - name: Give rights to execute
        run: |
          chmod 777 *
      - name: run NosyMouse tests against STAGING
        run: |
          ./nosymouse -action:run -pat:"2mjDoABTbk+WHZWZH0CG" -projectId:"98a61049-49f6-42bf-805d-11fd37e1f3b4" -scenarioId:"ed1bb01-a5ad-438f-9795-02aecaef31ca" -env:"STAGING" -url:"https://app.nosymouse.io"
