name: Main Workflow
on: [push]
jobs:
  build:
    name: Run NosyMouse tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get zip
        run: |
          curl https://github.com/myllil/NOSYMOUSE-CLI/blob/main/nosymouse-linux-x64.zip -L | unzip -q nosymouse-linux-x64.zip
      - name: show content
        run: |
          ls -la
      - name: Give rights to execute
        run: |
          chmod 777 *
      - name: run NosyMouse tests against STAGING
        run: |
          ./nosymouse -action:run -pat:"2mjDoABTbk+WHZWZH0CG" -projectId:"c98f5013-2063-41c2-a1ff-492291f51e53" -scenarioId:"d87ffddd-b887-4ad5-be17-e3838cef07fe" -env:"env1" -url:"https://app-dev.nosymouse.io"
