name: Main Workflow
on: [push]
jobs:
  build:
    name: Run NosyMouse tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get zip
        run: |
          curl https://github.com/myllil/NOSYMOUSE-CLI/blob/main/linux-64-092022.zip -L | unzip linux-64-092022.zip
      - name: show content
        run: |
          ls -la
      - name: Give rights to execute
        run: |
          chmod 777 *
      - name: run NosyMouse tests against STAGING
        run: |
         cd linux-x64 | ./nosymouse -action:run -pat:"2mjDoABTbk+WHZWZH0CG" -projectId:"98a61049-49f6-42bf-805d-11fd37e1f3b4" -scenarioId:"aed1bb01-a5ad-438f-9795-02aecaef31ca" -env:"STAGING" -url:"https://app.nosymouse.io"
